### ISSUE TITLE
missing libaio.so.1 with ubuntu-latest

### ISSUE THREAD

**Issue by rob975** [iamazeem/setup-oracle-instant-client-action#1]
When running on `ubuntu-latest` which currently is 24.04, sqlplus fails due to missing shared library `libaio.so.1`.

This is the snippet to reproduce the issue:
```yaml
jobs:
  test-sqlplus:
    runs-on: ubuntu-latest
    steps:
      - uses: iamazeem/setup-oracle-instant-client-action@v1
      - run: sqlplus -V
```

In `ubuntu-latest` the library is not installed and the name has changed. As a work-around I did:

```yaml
jobs:
  test-sqlplus:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install libaio1t64
          sudo ln -sr /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
      - uses: iamazeem/setup-oracle-instant-client-action@v1
      - run: sqlplus -V
```
